# Generated by Django 4.2.18 on 2026-03-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='documents/', verbose_name='Снимка на документа')),
                ('extracted_text', models.TextField(blank=True, null=True, verbose_name='Извлечен текст')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата на качване')),
            ],
        ),
    ]
